[project]
name = "anime-vector-service"
version = "0.1.0"
description = "Microservice for anime vector database operations with semantic search capabilities"
requires-python = ">=3.12"
dependencies = [
    # Core FastAPI dependencies
    "fastapi==0.115.13",
    "uvicorn==0.34.3",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.0",
    "python-dotenv>=1.1.0",
    # Vector database
    "qdrant-client[fastembed]==1.14.3",
    # Embedding models
    "sentence-transformers==5.0.0",
    "transformers==4.55.0",
    "torch>=2.0.0",
    "open-clip-torch>=2.29.0", # OpenCLIP for vision embeddings
    # Image processing
    "pillow>=11.2.1",
    # HTTP client for external requests
    "aiohttp==3.12.13",
    # Web scraping dependencies
    "cloudscraper>=1.2.71",
    "beautifulsoup4>=4.12.0",
    # Fine-tuning capabilities
    "peft==0.16.0",
    "huggingface-hub>=0.20.0", # For downloading from HuggingFace
    # HTTP dependencies
    "requests>=2.32.4",
    "rapidfuzz>=3.14.1",
    "jellyfish>=1.2.0",
    "jaconv>=0.4.0",
    "pykakasi>=2.3.0",
    "scikit-learn>=1.7.2",
    "crawl4ai>=0.7.4",
]

[project.optional-dependencies]
dev = [
    # Testing dependencies
    "pytest>=8.2.0",
    "pytest-asyncio==1.0.0",
    "httpx>=0.28.1",
    "pytest-cov==6.2.1",
    "pytest-mock==3.14.1",

    # Development dependencies
    "black>=24.0.0",
    "isort>=5.13.0",
    "autoflake>=2.3.0",
    "mypy>=1.18.1",

    # Pretty output formatting
    "rich>=13.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=src",
    "--cov-report=term-missing:skip-covered",
    "--cov-report=html:htmlcov",
    "--cov-fail-under=80"
]
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
]

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "isort>=6.0.1",
    "mypy>=1.18.1",
    "scikit-learn-stubs>=0.0.3",
    "scipy-stubs>=1.16.2.0",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-pillow>=10.2.0.20240822",
    "types-python-dateutil>=2.9.0.20250822",
    "types-requests>=2.32.4.20250913",
    "types-setuptools>=80.9.0.20250822",
]

[tool.mypy]
mypy_path = "stubs"
