name: Security Scanning

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run daily at 2 AM UTC to catch new vulnerabilities
    - cron: "0 2 * * *"

jobs:
  trivy-container-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t anime-vector-service:${{ github.sha }} \
            -f docker/Dockerfile .

      - name: Run Trivy vulnerability scanner on container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "anime-vector-service:${{ github.sha }}"
          format: "sarif"
          output: "trivy-container-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1" # Fail CI on critical/high vulnerabilities

      - name: Upload Trivy container scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-container-results.sarif"
          category: "container-scan"

  trivy-filesystem-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-fs-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: "0" # Don't fail CI, just report

      - name: Upload Trivy filesystem scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-fs-results.sarif"
          category: "filesystem-scan"

  trivy-config-scan:
    name: Trivy Config Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy configuration scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          format: "sarif"
          output: "trivy-config-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0" # Don't fail CI, just report

      - name: Upload Trivy config scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-config-results.sarif"
          category: "config-scan"
